project:
  type: website
  output-dir: _slides
  render: [index.qmd]
  pre-render: "R/_pre-render-revealjs.R"
  post-render: "R/_post-render-revealjs.R"

title: "Impact of climate change on child nutrition"
author: "Arthur R. MagalhÃ£es, Daniel Vartanian, & Aline M. de Carvalho"
institute: "Sustentarea"
date: today

format:
  revealjs:
    lang: en
    keyboard: true
    controls: true
    controls-layout: bottom-right
    preview-links: auto
    chalkboard: true
    csl: csl/english-apa-author-date.csl
    theme: [default, scss/slides.scss]
